### ISSUE TITLE
wow

### ISSUE THREAD

**Issue by yashash1511** [blueedgetechno/androidInReact#1]
I am unable to tell the difference on phone.
is this the next big thing

also why react 17 wen there is react18?
fontawesome5 wen there is v6

**Comment by yashash1511** [comment]
on laptop unable to open the QS menu

https://user-images.githubusercontent.com/89068816/166154949-d833b240-c95f-4fb5-8e75-8203549ef2b5.mp4

**Comment by yashash1511** [comment]
also how about android12 styled qs panel

![image](https://user-images.githubusercontent.com/89068816/166161111-c7c8191d-5eed-4d08-afc0-b06781779fa3.png)
![image](https://user-images.githubusercontent.com/89068816/166161116-d2093115-5af7-46b3-9989-a46752611359.png)

**Comment by blueedgetechno** [comment]
I tried sticking to one ui 4 but yes we can change the ui accordingly

**Comment by blueedgetechno** [comment]
let me add you add a contributor

**Comment by yashash1511** [comment]
> contributor

*collaborator
