### ISSUE TITLE
Black screen on Chrome

### ISSUE THREAD

**Issue by NowEwo** [blueedgetechno/androidInReact#30]
![Screenshot_2022-05-09-13-30-11-271_com.android.chrome.jpg](https://user-images.githubusercontent.com/77587065/167401175-928a9eaf-0d6b-451b-a930-c543d8f585fa.jpg)

**Comment by android69420** [comment]
Hey, thank you for creating an issue. We will normally respond within 24 hours.

**Comment by andrewstech** [comment]
Try clearing cache or loading in incognito
