### ISSUE TITLE
How I can add application ? I can ?

### ISSUE THREAD

**Issue by NowEwo** [blueedgetechno/androidInReact#4]

**Comment by yashash1511** [comment]
![image](https://user-images.githubusercontent.com/89068816/166192002-d7598ec7-b393-4c64-b127-1ea17001c368.png)
yes please tell how

**Comment by blueedgetechno** [comment]
There are two ways to do it,

- Follow a step by step process and program the UI and functionality of a code
- Or put a app that redirects to external link

Future score:
- A store system
- Load App from local system

**Comment by yannou000** [comment]
Is there a JavaScript command Like on Windows 11 in react ?

**Comment by blueedgetechno** [comment]
there is a JavaScript command in win11React?
... oh you mean changing the localStorage data. No, it is not yet implemented in this project.

**Comment by yannou000** [comment]
Oh ... Well that would be a function to add...

**Comment by yannou000** [comment]
Oh ... Well that would be a function to add ...
