### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by MelonicOverlord** [blueedgetechno/androidInReact#5]
# Black Screen Using Certain Browsers

#### Using Firefox (not tested any other browsers) on PC or Mobile causes there to just be a black screen with nothing on it. Chrome works fine however, both on PC and Mobile.

**Comment by Posandu** [comment]
It's because [this](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getBattery) API isn't supported from Firefox yet.

**Comment by trizau** [comment]
> It's because [Battery Status API](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getBattery) isn't supported from Firefox yet.

safari also doesn't support this API, so any apple device will have a black screen
